### ISSUE TITLE
Limit ability to burn token supply to token owners

### ISSUE THREAD

**Issue by mividtim** [fabrica-land/fabrica-contracts#18]
In the v3.1 contract implementations, the operator burning a token does not currently need to match the "from" address passed in as a parameter. This should be changed so that these two addresses have to match. This applies to both the `burn` and the `burnBatch` methods.

Thanks to William Cheung https://troublor.xyz/ for the bug report.

**Comment by fedepo** [comment]
thanks @Troublor ! [Troublor](https://github.com/Troublor)
